create table notes (
    id integer primary key generated by default as identity,
    note_title text not null,
    note_content text not null,
    modified TIMESTAMPTZ default now() not null,
    private_note boolean default false not null,
    admin integer references users(id) on delete cascade not null,
    campaign integer references campaigns(id) on delete cascade not null
);