create table tags (
    id integer primary key generated by default as identity,
    tag_name text not null,
    note integer references notes(id) on delete cascade not null,
    admin integer references users(id) on delete cascade not null,
);